name: GPU Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the GPU Docker image
      run: |
        TAG=$(date -u +%Y%m%d%H%M%S)

        docker build --no-cache \
          -f Dockerfile-gpu \
          --tag docker.io/deepwok/mase-docker-gpu:$TAG . || exit 1

        if [ "${{ secrets.DOCKER_HUB_PASSWORD }}" != "" ]; then
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login docker.io -u deepwok --password-stdin
          docker push docker.io/deepwok/mase-docker-gpu:$TAG
          docker tag docker.io/deepwok/mase-docker-gpu:$TAG docker.io/deepwok/mase-docker-gpu:latest
          docker push docker.io/deepwok/mase-docker-gpu:latest
          echo "MASE GPU Docker image pushed."
        else
          echo "Skipped pushing: DOCKER_HUB_PASSWORD secret not configured."
        fi
